### ISSUE TITLE
Gather town needs to be on landing page

### ISSUE THREAD

**Issue by ranjanan** [JuliaCon/juliacon-webapp#143]
We need to mention it on the landing page so people know about it.

**Comment by fingolfin** [comment]
What's the URL?

**Comment by ranjanan** [comment]
"""
# When and where are the conference socials? 
The conference socials will be hosted on Gathertown (check [eventbrite](https://www.eventbrite.com/x/137139721599/ )for the link)from 6 - 7:30 PM UTC on 28th, and 29th, and from 4 - 7:30 PM (along with posters) and 8 - 9:30 PM UTC on 30th. 
"""
