### ISSUE TITLE
Hope to post this on the JuliaCon Jobs Board

### ISSUE THREAD

**Issue by preclinical** [JuliaCon/juliacon-webapp#153]
Massachusetts Institute of Technology, Preclinical I&T

We are looking for an enthusiastic Julia developer to join our mission of evaluating new therapies using high throughput imaging analytics and transfer learning between clinical and preclinical data. If interested please check out the job posting below:

https://careers.peopleclick.com/careerscp/client_mit/external/en_US/gateway/viewFromLink.html?localeCode=en-us&jobPostId=21084

**Comment by ranjanan** [comment]
No worries, I'll add this right away. I'll also plug this in the jobs channel on discord.
