### ISSUE TITLE
Render markdown

### ISSUE THREAD

**Issue by travigd** [JuliaCon/juliacon-webapp#28]
We don't currently display Markdown (e.g., in talk descriptions and user biographies).

## Steps
* `npm install react-markdown`
* Wrap the talk descriptions and profile biographies in the `<Markdown />` component
* Make a pull request :^)

**Comment by mcmcgrath13** [comment]
@vishakha-a how is this going?

**Comment by philmartin1** [comment]
Hi, I found this while looking for an issue to make my first open source contribution. Let me know if I can help out

**Comment by vishakha-a** [comment]
> @vishakha-a how is this going?

Been juggling an overwhelming amount of work in the past few days. It will be done in a bit. If anyone can complete it today though, feel free to take it up. :)
