### ISSUE TITLE
Add iCal export for talks

### ISSUE THREAD

**Issue by travigd** [JuliaCon/juliacon-webapp#29]
I'd be nice to have a way to download `.ical` files to allow users to add talks to their personal calendars.

## Implementation Strategy
* Add an API route (`/api/talk/[id]/export`)
* Possibly use [ical-generator](https://www.npmjs.com/package/ical-generator) to generate the ical file format
  * Make sure to return the correct `Content-Type` header
* Add a link from the talk page to _Add to calendar_

**Comment by logankilpatrick** [comment]
This is supported in pretalx for what it's worth.

**Comment by aviks** [comment]
I found pretalx can give me a .ics file for each speaker, but I could not find a way to generate one for the entire conference, or for all workshops

**Comment by logankilpatrick** [comment]
It works, I just did it and added it to the Julia Lang public calendar.
