### ISSUE TITLE
[Page] Sponsor Page

### ISSUE THREAD

**Issue by aviks** [JuliaCon/juliacon-webapp#34]
For every sponsor, link to a landing page for the sponsor, that contains the following list of (optional) elements

0) The sponsor logo
1) A blurb about the sponsor
2) A highlighted link for more info
3) A pre-recorded video from the sponsor
4) An embed discord widget for a private chat with the sponsor. 

---
Change sponsor list to a vertical sidebar on the side of every page that includes every sponsor.

**Comment by travigd** [comment]
@aviks How are we sourcing the data? I think getting the data loaded (as a JSON blob) is a good first step for adding contributors. For now we can probably fake it with Lorem Ipsum.

**Comment by aviks** [comment]
Yes loading it as a json blob is a good idea. 

@logankilpatrick , @ranjanan could you please gather these for the sponsors you've been in contact with. Lets collect it in this information in this spreadsheet: https://docs.google.com/spreadsheets/d/1Eol9Kg7d9IatEePA0k0N_WJn21_Va8PrALK5nIqEOdc/edit?usp=sharing

**Comment by logankilpatrick** [comment]
@aviks just to confirm, we are making this landing page in the JuliaCon website correct?

**Comment by aviks** [comment]
Yes

**Comment by logankilpatrick** [comment]
Okay, I pinged Repl.it, Packt, and Sticker Mule.

**Comment by logankilpatrick** [comment]
@aviks "One question – what are you looking for in the pre-recorded video?  "- from Packt

**Comment by aviks** [comment]
It's optional, but just a marketing video that introduces the company to our audience.
