### ISSUE TITLE
Time says UTC, but is actually local time

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaCon/juliacon-webapp#44]
![image](https://user-images.githubusercontent.com/24885580/87210878-26a70200-c2e5-11ea-862c-f4bc28a0ca72.png)

Workshop is at 14 utc, not 10 - @MomirMilutinovic is this related to the pr you're working on?

**Comment by travigd** [comment]
I also just noticed this. I don't remember having this issue before but maybe it's just always been there.
