### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by travigd** [JuliaCon/juliacon-webapp#5]
It looks like we can do an integration with Discord using [WidgetBot](https://widgetbot.io/). I've played around with this a little bit in the codebase right now. I think it would be incredibly valuable to have the conference program and the chat in one place.

However, it's unclear as to whether or not we'll be able to restrict the Discord to only "registered" users. One approach might be require users to enter their confirmation code and confirm the with EventBrite API. We'd still probably have to have the Discord URL embedded somewhere (maybe in a production-only environment variable?) and theoretically, there's nothing stopping people from copying it and sending it elsewhere - but we aren't _that_ paranoid.

#### WidgetBot Observations
* You can join a server via WidgetBot as read-only even if you're not a member of that server (confusingly, you can type messages and hit enter, but the messages just get lost to the void).
* There doesn't seem to be a way to join the server via WidgetBot.
* We could embed an invite widget.
* We could also do authorization *via* [Discord OAuth2](https://discord.com/developers/docs/topics/oauth2). My concern with this approach is just that it's a bit indirect - the user has to first make a Discord account using the invite link and **then** they can log in to the on-site chat. We could do our best to include some instructions, but nonetheless...

**Comment by ranjanan** [comment]
We could make everyone create a discord account when we send them their confirmation code, and then authorize via Discord OAUth2

**Comment by ranjanan** [comment]
@aviks thoughts?

**Comment by travigd** [comment]
Conversation with JuliaCon Organizers:
* We should not allow the Discord chat to be viewed by people who have not registered and agreed to the community standard.
  * Other conferences has open chat (where you can view publicly but have to log in to post).
  * The Julia community seems to value privacy more, so at this point we're leaning towards just not having it open.
* Using Discord OAuth2 seems to be the better option.
* We should try to test this soon.

---

## Potential Approach
Ultimately, what I want to avoid is people getting confused about the interactions with Discord. This means avoiding having lots of indirection or telling users to "do X, then do Y, then do Z, in order"

What I'd like to do (assuming a brand new user to the site who hasn't authenticated with Discord already):
* When you open a talk video, there's a button to _Join the conversation with Discord_.
* When you click it, you are prompted to enter your JuliaCon ticket confirmation code along with a message about agreeing to community standards.
* On successfully verifying the code, prompt the user to login with Discord. This will request OAuth permissions to join servers on behalf of the user.
  * Automatically join the user to the JuliaCon Discord server
  * Possibly set their nick to the `${firstName} ${lastName}` (taken from EventBrite)
* Present the user with the Discord widget
  * This will still require them to login via the embedded iframe

As far as I can tell, that's the best we can do.

**Comment by zdroid** [comment]
If the streams will be live on YouTube, is Discord integration really needed?
