### ISSUE TITLE
Explore talks view - some typos... 

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/juliacon-webapp#52]
I've been playing with this - it's really cool!

<img width="996" alt="Screenshot 2020-07-18 at 09 22 33" src="https://user-images.githubusercontent.com/52289/87848437-6a4ace80-c8d8-11ea-8c01-d512bbe180f2.png">

[nitpick]

I noticed a few typos. For example:

"natural language procesing" , "isue", "proces", "mesage"

are the most noticeable...

I suppose these are typos in the original submissions? The original authors probably wouldn't mind having someone fix them ... ¯\\\_(ツ)_/¯ I'd be happy to fix a few.

I suppose the smaller words like "lot" and "tips" are there to make the word cloud look good... :)

**Comment by travigd** [comment]
These are sourced from Pretalx. If you want to identify the talks (you can Ctrl-F in the data/talks.json file) you can ping the owners to change. Or maybe just ping the organizers and ask if it can just be changed. :^)

Whatever we do it won't happen in this repository probably (unless we just want to manually remap these misspellings for the purpose of generating the word cloud).

**Comment by mcmcgrath13** [comment]
I do a little bit of the preprocessing to lightly stem words. I’ll check
later today if that might be causing some of the misspelling.

**Comment by mcmcgrath13** [comment]
@cormullion thanks for pointing this out!  It turns out the pair `"ss" => "s"` snuck into the replacement mapping and was causing _a lot_ of typos.  I've changed it over to only do whole word replacement now.
