### ISSUE TITLE
Current talk discord bot

### ISSUE THREAD

**Issue by aviks** [JuliaCon/juliacon-webapp#69]
It would be great to have a service that posts the talk name and speaker at the beginning of the talk to the relevant discord channel.

**Comment by christopher-dG** [comment]
I could help with this, but just need to clarify what's needed.

We have all the talk metadata so is it basically a matter of "for each talk, at \<start time> post to \<channel> with \<talk name> and \<speaker info>?

**Comment by travigd** [comment]
Yep. Probably include a link to the JuliaCon webapp as well.
