### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by aviks** [JuliaCon/juliacon-webapp#77]
I think we should serve the site from `https://live.juliacon.org`

I imagine the instructions from https://vercel.com/docs/v2/custom-domains will do? I'll do the DNS changes, @travigd you may have to change the settings on the app.

**Comment by travigd** [comment]
Sounds good

**Comment by aviks** [comment]
DNS setting done

```
$ dig live.juliacon.org
....
;; ANSWER SECTION:
live.juliacon.org.      1798    IN      CNAME   cname.vercel-dns.com.
cname.vercel-dns.com.   25      IN      A       76.76.21.21
```
