### ISSUE TITLE
Live talks

### ISSUE THREAD

**Issue by aviks** [JuliaCon/juliacon-webapp#78]
Most of our talks are recorded, but some are live. The live sessions should display the youtube video in live mode, ie, without doing any time shifts. This should be true of the workshop videos as well (which raises the question, will we have this ready for workshops starting friday? It's not essential, but might be nice to have. )

**Comment by travigd** [comment]
The live view should be "good enough" for that - and it wouldn't be a bad beta test since the primary mode of interaction is already Zoom.

Can you add the live videos to the Google Sheet where we're tracking that? As well as maybe a "live" flag. cc @ranjanan since we talked about this yesterday

**Comment by aviks** [comment]
The Video sheet already has Live tag for live talks. The URLS for the workshop are also in there

**Comment by aviks** [comment]
This does work as expected, i think.
