### ISSUE TITLE
Team & Contributions

### ISSUE THREAD

**Issue by travigd** [JuliaCon/juliacon-webapp#8]
Please leave a like on this issue if you'd like to contribute to the project. I will add you as a collaborator on this repository.

Note that by doing so, you must agree to the policies laid out in [CONTRIBUTING.md](https://github.com/travigd/JuliaCon2020/blob/master/CONTRIBUTING.md) and, importantly, abide by the [Julia Community Standards](https://julialang.org/community/standards/).

If there is anything you'd like to discuss about contributing to the project, please feel free to start a discussion in a comment below. :^)

**Comment by zdroid** [comment]
I'd like to enter. Just one thing, wouldn't it be better to move this into the JuliaCon org?

**Comment by travigd** [comment]
Great point. :^)

**Comment by travigd** [comment]
Actually, because of _reasons_, the project does need to exist under a personal account (Vercel limits deployments for projects under organizations to require a monthly payment per contributor).
