### ISSUE TITLE
A note saying "check your eventbrite email for workshop zoom links" 

### ISSUE THREAD

**Issue by ranjanan** [JuliaCon/juliacon-webapp#80]

**Comment by aviks** [comment]
Just add it to the abstract of all workshops in pretalx? It's only 10, might be the easiest option

**Comment by ranjanan** [comment]
Sure, can do.

**Comment by ranjanan** [comment]
Can you give me edit access on Pretalx, if you have that?

**Comment by ranjanan** [comment]
One problem with adding to abstracts in Pretalx is that there's a character limit of 500. and some speakers have filled that up.

**Comment by travigd** [comment]
We can add it on the web app instead then.

**Comment by ranjanan** [comment]
Ok I managed to add it to all abstracts, so you don't need to do this :-)
