### ISSUE TITLE
A little style?

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/juliacon-webapp#87]
I thought the schedule and poster pages could benefit from a hint of style... Something like:

<img width="1239" alt="Screenshot 2020-07-24 at 08 25 05" src="https://user-images.githubusercontent.com/52289/88369202-6bbc4100-cd87-11ea-9220-f6b6afa34c03.png">

Not much, but just a little bit of type hierarchy to guide the eye, and a hint of color to show that it's part of juliacon.

I thought about trying to contribute more than just this, but after looking at the HTML source I realise that I haven't a clue about modern web technology, and wouldn't be able to help.

For what it's worth, the CSS I added was:

```
@font-face {
  font-family: 'Patua One';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Patua One'), local('PatuaOne-Regular'), url(https://fonts.gstatic.com/s/patuaone/v10/ZXuke1cDvLCKLDcimxB44_luFgxbuQ.woff2) format('woff2'); 
}

a {
  outline: none;
  text-decoration: none;
  padding: 2px 1px 0;
}

a:link {
  color: rgb(40%, 0%, 50%);
}

a:visited {
   color: rgb(40%, 0%, 50%);
}

a:focus {
  border-bottom: 1px solid;
  background: #BAE498;
}

a:hover {
  border-bottom: 1px solid;     
  background: #CDFEAA;
}

a:active {
  background: #265301;
  color: #CDFEAA;
}

.css-116nlvg {
	font-family: 'Patua One';
	font-size: 2rem;
	padding-top: 0rem;
}

.css-1pzt0kk {
	font-family: 'Patua One';
	font-size: 1.25rem;
}
```

**Comment by cormullion** [comment]
The Posters page might work better using a CSS grid:

<img width="963" alt="Screenshot 2020-07-24 at 09 41 17" src="https://user-images.githubusercontent.com/52289/88374608-e5592c80-cd91-11ea-82e3-08fa97f58319.png">

**Comment by travigd** [comment]
I don't think changing the title colors is the right move (especially since that purple looks exactly like the default purple for visited links). I made some changes in e0b3426ed6ad2c4f57bc28fc0fb2f0910df43668.

**Comment by travigd** [comment]
<img width="1616" alt="Screen Shot 2020-07-24 at 8 23 51 AM" src="https://user-images.githubusercontent.com/773453/88407505-0d8f5e00-cd87-11ea-8662-6f8c292969a4.png">

**Comment by travigd** [comment]
<img width="1616" alt="Screen Shot 2020-07-24 at 8 25 03 AM" src="https://user-images.githubusercontent.com/773453/88407599-2e57b380-cd87-11ea-85d5-c94de448e560.png">

**Comment by cormullion** [comment]
It was literally a random-ish click to show what I meant- I’m not good with colour 😂😂

**Comment by travigd** [comment]
COLOR IS HARD!

I appreciate the kick to think harder about things. I like the addition of the new font!

I'm not terribly skilled at design but it's something I've had to learn to some extent. I highly recommend this [Refactoring UI](https://refactoringui.com/) "book". It's targeted mostly towards developers who want to know enough of the fundamentals to make their stuff look good.

**Comment by cormullion** [comment]
That's looking great! Thanks...

I"ll be cheeky and suggest a tiny little extra tweak, for the benefit of any dyslexic folks - move the underlining away from the letters in the links, just a fraction...

<img width="543" alt="Screenshot 2020-07-24 at 17 26 10" src="https://user-images.githubusercontent.com/52289/88413366-f8d8b780-cdd2-11ea-8928-7565e8ffebc2.png">
