### ISSUE TITLE
Add NF as sponsor

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCon/juliacon-webapp#95]
We added a special section for NF under sponsors and should do so via the JuliaCon web app as well.

**Comment by travigd** [comment]
<img width="1616" alt="Screen Shot 2020-07-27 at 10 57 48 AM" src="https://user-images.githubusercontent.com/773453/88574969-028f3480-cff8-11ea-889b-011d577d04eb.png">

ça marche?

**Comment by logankilpatrick** [comment]
I don’t know what that means but it looks great!
